### ISSUE TITLE
Prompt user before creating a new file/directory when following a link

### ISSUE THREAD

**Issue by firecat53** [Epistates/treemd#24]
Per the title.

**Comment by nicholasjpaterno** [comment]
Looking into this one now!

**Comment by nicholasjpaterno** [comment]
Should be addressed in `main` will ship in the next patch release

**Comment by firecat53** [comment]
1. Still not getting prompted before jumping to a non-existent file. It just creates the file/directory.
2. Markdown links without a file extension create a file without the .md extension.

**Comment by nicholasjpaterno** [comment]
@firecat53 thank you for your patience on this one! I found the issue!

In `follow_link_from_interactive()`, the code checks if a file is markdown by looking at the extension:
```rust
let is_markdown = path.extension()...unwrap_or(false);
```

For links like `[link](simple-file)`  with no extension, `unwrap_or(false)` treats it as non-markdown, so it goes to the else branch which sets `pending_editor_file` and opens in external editor - bypassing the file creation prompt in load_file. The external editor will of course create a file if it doesnt exist as well - on save.

**Comment by nicholasjpaterno** [comment]
Should be addressed in `main` will ship in the next patch release, tests work for me based on the `test.md` from the adjacent issue.
